[build]
# This is the command Netlify will run from the root of your repository.
# It installs the CLI and then builds the `ephemeral_web` package.
command = "cargo install dioxus-cli --force && dx build --release --platform web --package crates/scrubkit-web"

# as determined by the Dioxus CLI's default behavior.
publish = "target/dx/scrubkit-web/release/web/public"
