[build]
# This is the command Netlify will run from the root of your repository.
# It installs the CLI and then builds the `ephemeral_web` package.
command = "rustup default stable && cargo install dioxus-cli --force && cd crates/scrubkit-web && dx build --release --platform web"

# as determined by the Dioxus CLI's default behavior.
publish = "target/dx/scrubkit-web/release/web/public"


[build.environment]
# Set the Rust version Netlify should use
RUST_VERSION = "1.78"
